/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package loginandsignup;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JList;

/**
 *
 * @author JessicaS
 */
public class BookCollection extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BookCollection.class.getName());

    /**
     * Creates new form BookCollection
     */
    public BookCollection(UserDBOperator db_operator)
    {
        initComponents();
        this.db_operator = db_operator;
        // create the JList using model from DB Operator
        reading_list = new JList<>(db_operator.getBookNames());

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        to_read_label = new javax.swing.JLabel();
        num_reading = new javax.swing.JLabel();
        num_to_read = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        to_read_list = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        reading_list = new javax.swing.JList<>();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        finished_list = new javax.swing.JList<>();
        finished_label = new javax.swing.JLabel();
        num_finished = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Palatino", 1, 36)); // NOI18N
        jLabel1.setText("Books Collection");

        jLabel2.setText("Reading");

        to_read_label.setText("To-Read");

        num_reading.setText("(2)");

        num_to_read.setText("(7)");

        to_read_list.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        to_read_list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                to_read_listMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(to_read_list);

        reading_list.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        reading_list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reading_listMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(reading_list);

        jButton3.setText("Add New Book");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(num_reading)
                        .addGap(203, 203, 203)
                        .addComponent(to_read_label)
                        .addGap(18, 18, 18)
                        .addComponent(num_to_read))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(to_read_label)
                    .addComponent(num_reading)
                    .addComponent(num_to_read))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(jScrollPane4))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(40, 10, 510, 455);

        finished_list.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        finished_list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                finished_listMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(finished_list);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(560, 140, 158, 300);

        finished_label.setText("Finished");
        getContentPane().add(finished_label);
        finished_label.setBounds(590, 110, 49, 17);

        num_finished.setText("(10)");
        getContentPane().add(num_finished);
        num_finished.setBounds(650, 110, 20, 17);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void finished_listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_finished_listMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_finished_listMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void reading_listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reading_listMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_reading_listMouseClicked

    private void to_read_listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_to_read_listMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_to_read_listMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel finished_label;
    private javax.swing.JList<String> finished_list;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel num_finished;
    private javax.swing.JLabel num_reading;
    private javax.swing.JLabel num_to_read;
    private javax.swing.JList<String> reading_list;
    private javax.swing.JLabel to_read_label;
    private javax.swing.JList<String> to_read_list;
    // End of variables declaration//GEN-END:variables
    private UserDBOperator db_operator;
}
