/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package loginandsignup;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.io.File;
import javax.swing.ImageIcon;

/**
 *
 * @author JessicaS
 */
public class BookDetails extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BookDetails.class.getName());

    /**
     * Creates new form BookDetails
     */
    public BookDetails(UserDBOperator db_operator) { // neef a reference to db_operator which alr has the connection
        this.setVisible(true);
        Statement stmt;
        ResultSet rs;
        initComponents();
        this.db_operator = db_operator;
        img_file_chooser.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        book_image = new javax.swing.JLabel();
        author_text = new javax.swing.JTextField();
        book_title = new javax.swing.JLabel();
        title_text = new javax.swing.JTextField();
        num_of_pages = new javax.swing.JLabel();
        num_pages_text = new javax.swing.JTextField();
        book_author = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        create_btn = new javax.swing.JButton();
        img_file_chooser = new javax.swing.JFileChooser();
        upload_file_btn = new javax.swing.JButton();
        book_img = new javax.swing.JLabel();

        popupMenu1.setLabel("popupMenu1");
        popupMenu1.addActionListener(this::popupMenu1ActionPerformed);
        popupMenu1.getAccessibleContext().setAccessibleDescription("");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Palatino", 1, 36)); // NOI18N
        jLabel1.setText("CREATE NEW BOOK");

        book_image.setText("Image FIle");

        author_text.addActionListener(this::author_textActionPerformed);

        book_title.setText("Title");

        title_text.addActionListener(this::title_textActionPerformed);

        num_of_pages.setText("Number of Pages");

        num_pages_text.addActionListener(this::num_pages_textActionPerformed);

        book_author.setText("Author");

        jTextField4.addActionListener(this::jTextField4ActionPerformed);

        create_btn.setText("Create");
        create_btn.addActionListener(this::create_btnActionPerformed);

        img_file_chooser.setApproveButtonText("");
        img_file_chooser.setApproveButtonToolTipText("");
        img_file_chooser.setDialogTitle("");
        img_file_chooser.addActionListener(this::img_file_chooserActionPerformed);

        upload_file_btn.setText("Upload File");
        upload_file_btn.addActionListener(this::upload_file_btnActionPerformed);

        book_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginandsignup/_.jpeg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(book_title, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(title_text, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(create_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(num_pages_text, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(num_of_pages, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(book_author, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(author_text, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(book_image, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(upload_file_btn))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(book_img, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(394, 394, 394)
                        .addComponent(img_file_chooser, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(594, 594, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(book_title, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(title_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(img_file_chooser, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(num_of_pages, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(num_pages_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(book_author, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(author_text, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(book_image, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(upload_file_btn))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(book_img, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(1218, 1218, 1218)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(create_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(6, 0, 778, 507);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void author_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_author_textActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_author_textActionPerformed

    private void num_pages_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num_pages_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num_pages_textActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void create_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_btnActionPerformed
        // TODO add your handling code here:
        db_operator.setTitle(title_text.getText());
        db_operator.setNumPages(num_pages_text.getText());
        db_operator.setAuthor(author_text.getText());

        int book_valid = db_operator.createBook();
        if(book_valid != 0)
        {
            System.out.println("Book added successfully!");
        }

    }//GEN-LAST:event_create_btnActionPerformed

    private void title_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_title_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_title_textActionPerformed

    private void popupMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popupMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_popupMenu1ActionPerformed

    private void img_file_chooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_img_file_chooserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_img_file_chooserActionPerformed

    private void upload_file_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upload_file_btnActionPerformed
        // TODO add your handling code here:
        
        // select the users OWN file directory 
        
        img_file_chooser.setVisible(true);
        img_file_chooser.showSaveDialog(jPanel1);
        File img_file = img_file_chooser.getSelectedFile(); // get the file object of users selected file
        book_img.setIcon(new ImageIcon(img_file.getPath()));
        // change image to the selected file
        
    }//GEN-LAST:event_upload_file_btnActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField author_text;
    private javax.swing.JLabel book_author;
    private javax.swing.JLabel book_image;
    private javax.swing.JLabel book_img;
    private javax.swing.JLabel book_title;
    private javax.swing.JButton create_btn;
    private javax.swing.JFileChooser img_file_chooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel num_of_pages;
    private javax.swing.JTextField num_pages_text;
    private java.awt.PopupMenu popupMenu1;
    private javax.swing.JTextField title_text;
    private javax.swing.JButton upload_file_btn;
    // End of variables declaration//GEN-END:variables
    private UserDBOperator db_operator; 
}

