package loginandsignup;
import java.sql.ResultSet;
import java.sql.SQLException;
import loginandsignup.DBOperator;
import javax.swing.ImageIcon;
import java.io.IOException;
import javax.swing.SwingUtilities;


public class SingleBookInfo extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SingleBookInfo.class.getName());

    public SingleBookInfo(DBOperator db_operator, ResultSet details) {
        this.db_operator = db_operator;
        initComponents();
        this.details = details;
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        book_img = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        progress_bar = new javax.swing.JProgressBar();
        jLabel5 = new javax.swing.JLabel();
        book_name = new javax.swing.JLabel();
        book_author = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        back_btn = new javax.swing.JButton();
        users_completed = new javax.swing.JLabel();
        open_reading_notes_btn = new javax.swing.JButton();
        change_cover_btn = new javax.swing.JButton();
        edit_users_btn = new javax.swing.JButton();
        edit_name_btn = new javax.swing.JButton();
        edit_author_btn = new javax.swing.JButton();
        add_book_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Palatino", 0, 36)); // NOI18N
        jLabel1.setText("Book Details");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(44, 32, 254, 56);

        book_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginandsignup/_.jpeg"))); // NOI18N
        book_img.setText("jLabel2");
        jPanel1.add(book_img);
        book_img.setBounds(510, 90, 278, 320);

        jLabel3.setText("Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 120, 34, 17);

        jLabel4.setText("Author");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 190, 37, 17);
        jPanel1.add(progress_bar);
        progress_bar.setBounds(509, 32, 240, 39);

        jLabel5.setText("Reading Progress");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(388, 42, 103, 17);

        book_name.setText("Insert Name");
        jPanel1.add(book_name);
        book_name.setBounds(131, 117, 260, 17);

        book_author.setText("Insert Author");
        jPanel1.add(book_author);
        book_author.setBounds(130, 190, 263, 17);

        jLabel8.setText("Users Finished");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(50, 250, 87, 17);

        back_btn.setText("Back to Book Collection");
        back_btn.addActionListener(this::back_btnActionPerformed);
        jPanel1.add(back_btn);
        back_btn.setBounds(40, 440, 189, 39);

        users_completed.setText("Insert # Users");
        jPanel1.add(users_completed);
        users_completed.setBounds(160, 250, 220, 17);

        open_reading_notes_btn.setText("Open Reading Notes");
        open_reading_notes_btn.addActionListener(this::open_reading_notes_btnActionPerformed);
        jPanel1.add(open_reading_notes_btn);
        open_reading_notes_btn.setBounds(40, 340, 200, 60);

        change_cover_btn.setText("Change Book Cover");
        jPanel1.add(change_cover_btn);
        change_cover_btn.setBounds(510, 420, 160, 23);

        edit_users_btn.setText("Edit");
        jPanel1.add(edit_users_btn);
        edit_users_btn.setBounds(400, 250, 78, 23);

        edit_name_btn.setText("Edit");
        edit_name_btn.addActionListener(this::edit_name_btnActionPerformed);
        jPanel1.add(edit_name_btn);
        edit_name_btn.setBounds(400, 110, 72, 23);

        edit_author_btn.setText("Edit");
        edit_author_btn.addActionListener(this::edit_author_btnActionPerformed);
        jPanel1.add(edit_author_btn);
        edit_author_btn.setBounds(400, 180, 78, 23);

        add_book_btn.setText("Add Book To Collection");
        add_book_btn.addActionListener(this::add_book_btnActionPerformed);
        jPanel1.add(add_book_btn);
        add_book_btn.setBounds(300, 340, 190, 60);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 800, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        BookCollection book_collection = new BookCollection(db_operator);
        
    }//GEN-LAST:event_back_btnActionPerformed

    private void open_reading_notes_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_open_reading_notes_btnActionPerformed
        // open reading notes window & use overloaded method to give the specific book 
    }//GEN-LAST:event_open_reading_notes_btnActionPerformed

   private void setBookDetails() // JOIN BOOKS & USERBOOKS
    {
        // db_operator queries for the resultset to get all info at once
        try{
            
        details = db_operator.getFullBookDetails(details.getString("book_name"));
        
        // INVOKE LATER
        
        // try catch have to be specific to the inside method
        
            // call helper function for editing other labels 
            book_name.setText(details.getString("book_name"));
            book_author.setText(details.getString("author"));
            //book_img
            book_img.setIcon(new ImageIcon(details.getBlob("book_img").getBinaryStream().readAllBytes()));
      
            // setup the progress bar
            users_completed.setText(String.valueOf(details.getInt("total_users_read")));
            progress_bar.setMinimum(0);
            progress_bar.setMaximum(details.getInt("num_pages"));
            progress_bar.setValue(details.getInt("page_progress"));
        }
        catch(SQLException e)
        {
            System.out.println("Someething went wrong when trying to query for book details");
            e.printStackTrace();
        }
        catch(IOException e)
        {
            e.printStackTrace();
        } 
   }
            
    private void edit_name_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_name_btnActionPerformed
        // set book name with popup 
    }//GEN-LAST:event_edit_name_btnActionPerformed

    private void edit_author_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_author_btnActionPerformed
        //
    }//GEN-LAST:event_edit_author_btnActionPerformed

    private void add_book_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_book_btnActionPerformed
        // TODO add your handling code here:
        // set values before func call
        db_operator.setPageProgress(progress_bar.getValue());
       // db_operator.setAuthor();
    
        db_operator.addBookToUserBooks();
     
    }//GEN-LAST:event_add_book_btnActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_book_btn;
    private javax.swing.JButton back_btn;
    private javax.swing.JLabel book_author;
    private javax.swing.JLabel book_img;
    private javax.swing.JLabel book_name;
    private javax.swing.JButton change_cover_btn;
    private javax.swing.JButton edit_author_btn;
    private javax.swing.JButton edit_name_btn;
    private javax.swing.JButton edit_users_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton open_reading_notes_btn;
    private javax.swing.JProgressBar progress_bar;
    private javax.swing.JLabel users_completed;
    // End of variables declaration//GEN-END:variables
    private DBOperator db_operator;
    private ResultSet details;
}
