package loginandsignup;
import java.sql.ResultSet;
import java.sql.SQLException;
import loginandsignup.DBOperator;
import javax.swing.ImageIcon;
import java.io.IOException;
import javax.swing.SwingUtilities;
import java.io.File;
import java.io.IOException;
import javax.swing.DefaultListModel;


public class SingleBookInfo extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SingleBookInfo.class.getName());

    public SingleBookInfo(DBOperator db_operator, ResultSet details, WindowManager manager){
        this.db_operator = db_operator;
        initComponents();
        this.setVisible(true);
        img_file_chooser.setVisible(false);
        this.pack();
        this.setLocationRelativeTo(null);
        this.manager = manager;
        this.details = details;
        setBookDetails();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        img_file_chooser = new javax.swing.JFileChooser();
        BookDetailsPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        book_img = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        book_name = new javax.swing.JLabel();
        book_author = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        back_btn = new javax.swing.JButton();
        users_completed = new javax.swing.JLabel();
        open_reading_notes_btn = new javax.swing.JButton();
        change_cover_btn = new javax.swing.JButton();
        edit_users_btn = new javax.swing.JButton();
        edit_name_btn = new javax.swing.JButton();
        edit_author_btn = new javax.swing.JButton();
        add_book_btn = new javax.swing.JButton();
        collection_selector = new javax.swing.JComboBox<>();
        remove_from_collection_btn = new javax.swing.JButton();
        progress_bar = new javax.swing.JProgressBar();
        jLabel5 = new javax.swing.JLabel();
        shelf_name = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        img_file_chooser.setDialogTitle("");
        img_file_chooser.addActionListener(this::img_file_chooserActionPerformed);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Palatino", 0, 36)); // NOI18N
        jLabel1.setText("Book Details");

        book_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginandsignup/_.jpeg"))); // NOI18N
        book_img.setText("jLabel2");

        jLabel3.setText("Name");

        jLabel4.setText("Author");

        book_name.setText("Insert Name");
        book_name.setPreferredSize(new java.awt.Dimension(310, 17));

        book_author.setText("Insert Author");
        book_author.setPreferredSize(new java.awt.Dimension(273, 17));

        jLabel8.setText("Users Finished");

        back_btn.setText("Back to Book Collection");
        back_btn.addActionListener(this::back_btnActionPerformed);

        users_completed.setText("Insert # Users");
        users_completed.setPreferredSize(new java.awt.Dimension(220, 17));

        open_reading_notes_btn.setText("Open Reading Notes");
        open_reading_notes_btn.addActionListener(this::open_reading_notes_btnActionPerformed);

        change_cover_btn.setText("Change Book Cover");
        change_cover_btn.addActionListener(this::change_cover_btnActionPerformed);

        edit_users_btn.setText("Edit");

        edit_name_btn.setText("Edit");
        edit_name_btn.addActionListener(this::edit_name_btnActionPerformed);

        edit_author_btn.setText("Edit");
        edit_author_btn.addActionListener(this::edit_author_btnActionPerformed);

        add_book_btn.setText("Add Book To Collection");
        add_book_btn.addActionListener(this::add_book_btnActionPerformed);

        collection_selector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Reading", "To-Read", "Finished" }));
        collection_selector.setSelectedItem(collection_selector);
        collection_selector.setToolTipText("Change List");
        collection_selector.addActionListener(this::collection_selectorActionPerformed);

        remove_from_collection_btn.setText("Remove From Collection");
        remove_from_collection_btn.addActionListener(this::remove_from_collection_btnActionPerformed);

        progress_bar.setPreferredSize(new java.awt.Dimension(240, 39));

        jLabel5.setText("Reading Progress");

        shelf_name.setText("Current Location");

        jButton1.setText("Save Details");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout BookDetailsPanelLayout = new javax.swing.GroupLayout(BookDetailsPanel);
        BookDetailsPanel.setLayout(BookDetailsPanelLayout);
        BookDetailsPanelLayout.setHorizontalGroup(
            BookDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookDetailsPanelLayout.createSequentialGroup()
                .addGroup(BookDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BookDetailsPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(BookDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(BookDetailsPanelLayout.createSequentialGroup()
                                .addGap(380, 380, 380)
                                .addComponent(edit_author_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(BookDetailsPanelLayout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(book_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8)
                            .addGroup(BookDetailsPanelLayout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(book_author, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(BookDetailsPanelLayout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addComponent(users_completed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(BookDetailsPanelLayout.createSequentialGroup()
                                .addGap(380, 380, 380)
                                .addComponent(edit_users_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(BookDetailsPanelLayout.createSequentialGroup()
                                .addGap(380, 380, 380)
                                .addComponent(edit_name_btn))
                            .addComponent(jLabel3)
                            .addGroup(BookDetailsPanelLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(BookDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(BookDetailsPanelLayout.createSequentialGroup()
                                        .addComponent(shelf_name, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(collection_selector, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(progress_bar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26))
                                    .addGroup(BookDetailsPanelLayout.createSequentialGroup()
                                        .addGap(333, 333, 333)
                                        .addComponent(jLabel5))))
                            .addGroup(BookDetailsPanelLayout.createSequentialGroup()
                                .addGroup(BookDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(BookDetailsPanelLayout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(open_reading_notes_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(61, 61, 61)
                                        .addGroup(BookDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(remove_from_collection_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(add_book_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(BookDetailsPanelLayout.createSequentialGroup()
                                        .addGap(175, 175, 175)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(30, 30, 30)
                                .addComponent(book_img, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(BookDetailsPanelLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(281, 281, 281)
                        .addComponent(change_cover_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        BookDetailsPanelLayout.setVerticalGroup(
            BookDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookDetailsPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(BookDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BookDetailsPanelLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(progress_bar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11))
                    .addGroup(BookDetailsPanelLayout.createSequentialGroup()
                        .addGroup(BookDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(shelf_name)
                            .addComponent(collection_selector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(BookDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(book_img, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(BookDetailsPanelLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel4))
                    .addGroup(BookDetailsPanelLayout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel8))
                    .addGroup(BookDetailsPanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel3))
                    .addGroup(BookDetailsPanelLayout.createSequentialGroup()
                        .addGroup(BookDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BookDetailsPanelLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(book_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(BookDetailsPanelLayout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(book_author, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(BookDetailsPanelLayout.createSequentialGroup()
                                .addGap(160, 160, 160)
                                .addComponent(users_completed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(BookDetailsPanelLayout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(edit_author_btn))
                            .addGroup(BookDetailsPanelLayout.createSequentialGroup()
                                .addGap(160, 160, 160)
                                .addComponent(edit_users_btn))
                            .addGroup(BookDetailsPanelLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(edit_name_btn)))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(BookDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BookDetailsPanelLayout.createSequentialGroup()
                                .addComponent(add_book_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(remove_from_collection_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(open_reading_notes_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(2, 2, 2)
                .addGroup(BookDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BookDetailsPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(change_cover_btn)))
        );

        collection_selector.getAccessibleContext().setAccessibleDescription("");

        getContentPane().add(BookDetailsPanel);
        BookDetailsPanel.setBounds(0, 0, 800, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        manager.editWindowVisibility(true, manager.getBookCollectionWindow());
        
        
    }//GEN-LAST:event_back_btnActionPerformed

    public String setOldShelfType(String shelf_type)
    {
        old_shelf_type = shelf_type;
        return old_shelf_type;
    }
    
    private void open_reading_notes_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_open_reading_notes_btnActionPerformed
        // open reading notes window & use overloaded method to give the specific book 
    }//GEN-LAST:event_open_reading_notes_btnActionPerformed

   private void setBookDetails() // JOIN BOOKS & USERBOOKS
    {
        // db_operator queries for the resultset to get all info at once
        try{
        
        details = db_operator.getFullBookDetails(details.getInt("book_id"));
        System.out.println("Book id: " + details.getInt("book_id"));
        System.out.println("Page progress: " + details.getInt("page_progress"));
        System.out.println("Book name: " + details.getString("book_name"));
        collection_selector.setSelectedItem(details.getString("shelf_type"));
        book_name.setText(details.getString("book_name"));
        book_author.setText(details.getString("author"));
        users_completed.setText(String.valueOf(details.getInt("total_users_read")));
        progress_bar.setMinimum(0);
        progress_bar.setMaximum(details.getInt("num_pages"));
        progress_bar.setValue(details.getInt("page_progress")); // must check using a condition for the edit

        if(details.getBytes("image") != null)
        {
                
                book_img.setIcon(new ImageIcon(details.getBytes("image")));
                
            
        }
        else
        {
            System.out.println("No image found in database");
        }
      
            // setup the progress bar        
        }
        catch(SQLException e)
        {
            System.out.println("Something went wrong when trying to query for book details");
            e.printStackTrace();
        }
   }
            
    private void edit_name_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_name_btnActionPerformed
        // set book name with popup 
    }//GEN-LAST:event_edit_name_btnActionPerformed

    private void edit_author_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_author_btnActionPerformed
        // change boolean edits made to true in order to call the option pane display
    }//GEN-LAST:event_edit_author_btnActionPerformed

    private void add_book_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_book_btnActionPerformed

        // set values before func call USE UPDATE FOR RESULTSET INSTEAD!!
        try{
        db_operator.setShelfType(collection_selector.getSelectedItem().toString());

        db_operator.setBookId(details.getInt("book_id")); 
        db_operator.setPageProgress(progress_bar.getValue());
        db_operator.setAuthor(book_author.getText());
        db_operator.setTitle(book_name.getText());
        db_operator.setNumUsersRead(Integer.parseInt(users_completed.getText()));
        db_operator.setBLOBImageFile(details.getBytes("image"));
    
        // must update even if no changes because its not guaranteed that there were no total edits (unless u add a condition in the edits buttons)
        //db_operator.updateBooksColumns();
        //db_operator.updateUsersBooksColumns();
        details = db_operator.getFullBookDetails(details.getInt("book_id")); // create a helper method
        int added_book_id = db_operator.addBookToUserBooks(details);
        if(added_book_id != 0)
        {
            System.out.println("Successfully added book to UserBooks!");
            // update the list model
            update_collection_lists("switch", old_shelf_type);
        }
        }
        catch(SQLException e)
        {
            System.out.println("Something went wrong when trying to query the book_id");
            e.printStackTrace();
        }

    }//GEN-LAST:event_add_book_btnActionPerformed

    private void update_collection_lists(String action)
    {   DefaultListModel<String> list = manager.getBookCollectionWindow().getListReference(collection_selector.getSelectedItem().toString());
        String name = book_name.getText();

        switch(action)
        {
            case "add":
                list.addElement(name);
            case "remove":
                list.removeElement(name);
        }
    }
    
    private void update_collection_lists(String action, String previous_shelf)
    {   
        DefaultListModel<String> prev_shelf_list = manager.getBookCollectionWindow().getListReference(previous_shelf);
        DefaultListModel<String> list = manager.getBookCollectionWindow().getListReference(collection_selector.getSelectedItem().toString());
        String name = book_name.getText();
        prev_shelf_list.removeElement(name);
        list.addElement(name);
   
    }
    
    private void change_cover_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_change_cover_btnActionPerformed
        img_file_chooser.setVisible(true);

        img_file_chooser.showOpenDialog(BookDetailsPanel);
        book_img_file = new File(img_file_chooser.getSelectedFile().getPath());
        if(book_img_file != null)
        {
            book_img.setIcon(new ImageIcon(book_img_file.getPath()));
        }
  
    }//GEN-LAST:event_change_cover_btnActionPerformed

    private void remove_from_collection_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remove_from_collection_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_remove_from_collection_btnActionPerformed

    private void collection_selectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_collection_selectorActionPerformed
        

    }//GEN-LAST:event_collection_selectorActionPerformed

    private void img_file_chooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_img_file_chooserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_img_file_chooserActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BookDetailsPanel;
    private javax.swing.JButton add_book_btn;
    private javax.swing.JButton back_btn;
    private javax.swing.JLabel book_author;
    private javax.swing.JLabel book_img;
    private javax.swing.JLabel book_name;
    private javax.swing.JButton change_cover_btn;
    private javax.swing.JComboBox<String> collection_selector;
    private javax.swing.JButton edit_author_btn;
    private javax.swing.JButton edit_name_btn;
    private javax.swing.JButton edit_users_btn;
    private javax.swing.JFileChooser img_file_chooser;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton open_reading_notes_btn;
    private javax.swing.JProgressBar progress_bar;
    private javax.swing.JButton remove_from_collection_btn;
    private javax.swing.JLabel shelf_name;
    private javax.swing.JLabel users_completed;
    // End of variables declaration//GEN-END:variables
    private DBOperator db_operator;
    private ResultSet details;
    private File book_img_file;
    boolean edits_made;
    private WindowManager manager;
    private byte[] blob_file;
    private String old_shelf_type;
}
