/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package loginandsignup;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author JessicaS
 */
public class SingleBookInfo extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SingleBookInfo.class.getName());

    /**
     * Creates new form SingleBookInfo
     */
    public SingleBookInfo(UserDBOperator db_operator) {
        this.db_operator = db_operator;
        initComponents();
    }
    
    public initializeBookInfo()
    {
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        book_img = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        progress_bar = new javax.swing.JProgressBar();
        jLabel5 = new javax.swing.JLabel();
        book_name = new javax.swing.JLabel();
        book_author = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        back_btn = new javax.swing.JButton();
        users_completed = new javax.swing.JLabel();
        open_reading_notes_btn = new javax.swing.JButton();
        change_cover_btn = new javax.swing.JButton();
        edit_users_btn = new javax.swing.JButton();
        edit_name_btn = new javax.swing.JButton();
        edit_author_btn = new javax.swing.JButton();
        add_book_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Palatino", 0, 36)); // NOI18N
        jLabel1.setText("Book Details");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(44, 32, 254, 56);

        book_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginandsignup/_.jpeg"))); // NOI18N
        book_img.setText("jLabel2");
        jPanel1.add(book_img);
        book_img.setBounds(520, 110, 278, 320);

        jLabel3.setText("Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 120, 34, 17);

        jLabel4.setText("Author");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 190, 37, 17);
        jPanel1.add(progress_bar);
        progress_bar.setBounds(509, 32, 240, 39);

        jLabel5.setText("Reading Progress");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(388, 42, 103, 17);

        book_name.setText("Insert Name");
        jPanel1.add(book_name);
        book_name.setBounds(131, 117, 260, 17);

        book_author.setText("Insert Author");
        jPanel1.add(book_author);
        book_author.setBounds(130, 190, 263, 17);

        jLabel8.setText("Users Finished");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(50, 250, 87, 17);

        back_btn.setText("Back to Book Collection");
        back_btn.addActionListener(this::back_btnActionPerformed);
        jPanel1.add(back_btn);
        back_btn.setBounds(40, 450, 189, 39);

        users_completed.setText("Insert # Users");
        jPanel1.add(users_completed);
        users_completed.setBounds(160, 250, 220, 17);

        open_reading_notes_btn.setText("Open Reading Notes");
        open_reading_notes_btn.addActionListener(this::open_reading_notes_btnActionPerformed);
        jPanel1.add(open_reading_notes_btn);
        open_reading_notes_btn.setBounds(40, 340, 200, 60);

        change_cover_btn.setText("Change Book Cover");
        jPanel1.add(change_cover_btn);
        change_cover_btn.setBounds(520, 450, 160, 23);

        edit_users_btn.setText("Edit");
        jPanel1.add(edit_users_btn);
        edit_users_btn.setBounds(400, 250, 78, 23);

        edit_name_btn.setText("Edit");
        edit_name_btn.addActionListener(this::edit_name_btnActionPerformed);
        jPanel1.add(edit_name_btn);
        edit_name_btn.setBounds(400, 110, 72, 23);

        edit_author_btn.setText("Edit");
        edit_author_btn.addActionListener(this::edit_author_btnActionPerformed);
        jPanel1.add(edit_author_btn);
        edit_author_btn.setBounds(400, 180, 78, 23);

        add_book_btn.setText("Add Book To Collection");
        add_book_btn.addActionListener(this::add_book_btnActionPerformed);
        jPanel1.add(add_book_btn);
        add_book_btn.setBounds(300, 340, 190, 60);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 848, 498);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        BookCollection book_collection = new BookCollection(db_operator);
        
    }//GEN-LAST:event_back_btnActionPerformed

    private void open_reading_notes_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_open_reading_notes_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_open_reading_notes_btnActionPerformed

    private ResultSet get_book_details() // JOIN BOOKS & USERBOOKS
    {
        // db_operator queries for the resultset
        
        // call helper function for editing other labels 
    }
            
    private void edit_name_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_name_btnActionPerformed
        // TODO add your handling code here:
        // call getBookName from db operator
    }//GEN-LAST:event_edit_name_btnActionPerformed

    private void edit_author_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_author_btnActionPerformed
        // TODO add your handling code here:
        // call getAuthorName from db operator 
    }//GEN-LAST:event_edit_author_btnActionPerformed

    private void add_book_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_book_btnActionPerformed
        // TODO add your handling code here:
        // set values before func call
        db_operator.setPageProgress(progress_bar.getValue());
        db_operator.setAuthor();
    
        db_operator.addBookToUserBooks();
     
    }//GEN-LAST:event_add_book_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SingleBookInfo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_book_btn;
    private javax.swing.JButton back_btn;
    private javax.swing.JLabel book_author;
    private javax.swing.JLabel book_img;
    private javax.swing.JLabel book_name;
    private javax.swing.JButton change_cover_btn;
    private javax.swing.JButton edit_author_btn;
    private javax.swing.JButton edit_name_btn;
    private javax.swing.JButton edit_users_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton open_reading_notes_btn;
    private javax.swing.JProgressBar progress_bar;
    private javax.swing.JLabel users_completed;
    // End of variables declaration//GEN-END:variables
    private UserDBOperator db_operator;
}
