package code_files;

import javax.swing.JOptionPane;
import java.awt.Dialog;
import java.awt.Desktop;
import java.net.URI;
import javax.swing.event.HyperlinkEvent;
import javax.swing.event.HyperlinkListener;
import javax.swing.JEditorPane;
import java.io.*;

public class AnnouncementsPage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AnnouncementsPage.class.getName());

     public AnnouncementsPage(WindowManager manager, DBOperator db_operator, Validator validator) {
       this.manager = manager;
       this.db_operator = db_operator;
       this.validator = validator;
       initComponents();
       loadAnnouncement();
       roleCheck();
       this.pack();
       this.setLocationRelativeTo(null);
       this.setVisible(true);
    }
    
    public void roleCheck()
    {
        System.out.println("User at role check is " + db_operator.getUser().getName());
        System.out.println(db_operator.getUser().isAdmin());
        save_btn.setVisible(db_operator.getUser().isAdmin());
        announcement_field.setEditable(db_operator.getUser().isAdmin());
        edit_meeting_btn.setVisible(db_operator.getUser().isAdmin());

    }
    
    
    public void loadAnnouncement()
    {
        this.announcement = db_operator.loadAnnouncement();
        announcement_field.setText(announcement.getText());
        author_label.setText(db_operator.getUserName(announcement.getUserId()));
        date_label.setText(announcement.getDate());
        
    }

 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        option_pane = new javax.swing.JOptionPane();
        jPanel1 = new javax.swing.JPanel();
        join_meeting_btn = new javax.swing.JButton();
        back_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        save_btn = new javax.swing.JButton();
        last_edited = new javax.swing.JLabel();
        date_label = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        author_label = new javax.swing.JLabel();
        edit_meeting_btn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        announcement_field = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 500));
        setSize(new java.awt.Dimension(800, 500));

        jPanel1.setBackground(new java.awt.Color(255, 248, 234));
        jPanel1.setDoubleBuffered(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));

        join_meeting_btn.setText("CLICK TO JOIN MEETING");
        join_meeting_btn.addActionListener(this::join_meeting_btnActionPerformed);

        back_btn.setText("BACK");
        back_btn.addActionListener(this::back_btnActionPerformed);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        jLabel1.setText("Announcements");

        save_btn.setText("Save Announcement");
        save_btn.addActionListener(this::save_btnActionPerformed);

        last_edited.setText("Last Edited At:");

        date_label.setText("Insert Date Here");

        jLabel4.setText("Author: ");

        author_label.setText("Insert Author Name");

        edit_meeting_btn.setText("Edit");
        edit_meeting_btn.addActionListener(this::edit_meeting_btnActionPerformed);

        announcement_field.setColumns(20);
        announcement_field.setRows(5);
        jScrollPane2.setViewportView(announcement_field);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(back_btn)
                        .addGap(700, 700, 700))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(edit_meeting_btn))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 244, Short.MAX_VALUE)
                                .addComponent(join_meeting_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(31, 31, 31)
                                .addComponent(author_label)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(78, 78, 78))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(last_edited)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(date_label)
                        .addGap(259, 259, 259)
                        .addComponent(save_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(edit_meeting_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(join_meeting_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(back_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(author_label, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(save_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(last_edited)
                    .addComponent(date_label))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 811, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void join_meeting_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_join_meeting_btnActionPerformed

        editorPane.setContentType("text/html");
        editorPane.setEditable(false);
        editorPane.setText("<html>"+"<a href="+"'"+meeting_link+"'"+">Join Meeting</a>"+"</html>");
        
        editorPane.addHyperlinkListener(new HyperlinkListener(){
            public void hyperlinkUpdate(HyperlinkEvent e){
                if (e.getEventType()==HyperlinkEvent.EventType.ACTIVATED){
                    try{
                        Desktop.getDesktop().browse(new URI(e.getURL().toString()));
                    } catch (Exception ex){
                        ex.printStackTrace();
                    }
                }
            }
        });
        JOptionPane.showMessageDialog(this,editorPane,"MEETING LINK",JOptionPane.PLAIN_MESSAGE);
        
    }//GEN-LAST:event_join_meeting_btnActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        if(!announcement_field.getText().equals(announcement.getText())) // edits have been made
        {
            if(validator.changesSaved() == true) // valid, no unsaved changes
            {
                manager.getMenuWindow().setVisible(true);
                this.setVisible(false);
            }
            else
            {
                manager.showErrorMessage(option_pane, "You have unsaved changes!");
            }
        }
        else
        {
          manager.getMenuWindow().setVisible(true);
          this.setVisible(false);
        }
    }//GEN-LAST:event_back_btnActionPerformed

    private void save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_btnActionPerformed
    if(!announcement_field.getText().equals(announcement.getText()))
    {
        int val = db_operator.saveAnnouncement(new Announcement(db_operator.getUser().getUserId(), announcement_field.getText(), null));
        if(val == 1)
        {
            manager.showPlainMessage(option_pane, "Saved successfully!");
            // refresh labels
            announcement = db_operator.loadAnnouncement(); // need to request the date again
            author_label.setText(db_operator.getUserName(announcement.getUserId()));
            date_label.setText(announcement.getDate());
        }
        else
        {
            manager.showErrorMessage(option_pane, "Something went wrong, could not save announcement.");
        }
    }
    }//GEN-LAST:event_save_btnActionPerformed

    private void edit_meeting_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_meeting_btnActionPerformed
    // set changes made to true when saving
    String new_link = manager.showInputMessage(option_pane, "Enter the new meeting link:");
   if(!validator.isEmpty(new_link))
   {
        meeting_link = new_link;
        int val = db_operator.saveLink(meeting_link);
        if(val == 1)
        {
            manager.showPlainMessage(option_pane, "Link updated successfully!");
        }
        else
        {
            manager.showErrorMessage(option_pane, "Something went wrong, could not update link.");
        }        

   }
   else
   {
       manager.showErrorMessage(option_pane, "That is not a valid link!");
   }   
    }//GEN-LAST:event_edit_meeting_btnActionPerformed

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea announcement_field;
    private javax.swing.JLabel author_label;
    private javax.swing.JButton back_btn;
    private javax.swing.JLabel date_label;
    private javax.swing.JButton edit_meeting_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton join_meeting_btn;
    private javax.swing.JLabel last_edited;
    private javax.swing.JOptionPane option_pane;
    private javax.swing.JButton save_btn;
    // End of variables declaration//GEN-END:variables
    private WindowManager manager;
    private DBOperator db_operator;
    private Announcement announcement;
    private Validator validator;
    private String meeting_link = db_operator.getLink();
    private JEditorPane editorPane = new JEditorPane();

}
