package code_files;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import code_files.DBOperator;
import java.sql.SQLException;
import java.sql.ResultSet;

public class BookCollection extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BookCollection.class.getName());

    /**
     * Creates new form BookCollection
     */
    public BookCollection(WindowManager manager, DBOperator db_operator)
    {
        initComponents();
        this.pack();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.manager = manager;
        this.db_operator = db_operator;
        
        // initialize list models based on most recent db info
        configureListModels();
    }
    
    public void configureListModels()
    {
        reading_list.setModel(db_operator.getBookNames("Reading"));
        to_read_list.setModel(db_operator.getBookNames("To-Read"));
        finished_list.setModel(db_operator.getBookNames("Finished"));
    }
    
    public DefaultListModel<String> getListReference(String shelf_type)
    {
        // adjust logic later for user vs club books
        switch(shelf_type)
        {
            case "Reading":
                return (DefaultListModel<String>)reading_list.getModel();
            case "To-Read":
                return (DefaultListModel<String>)to_read_list.getModel();
            case "Finished":
                return (DefaultListModel<String>)finished_list.getModel();
        }
        return null;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        to_read_label = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        to_read_list = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        reading_list = new javax.swing.JList<>();
        create_book_btn = new javax.swing.JButton();
        finished_label = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        finished_list = new javax.swing.JList<>();
        search_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 500));
        setPreferredSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(158, 118, 118));

        jLabel1.setBackground(new java.awt.Color(255, 248, 234));
        jLabel1.setFont(new java.awt.Font("Palatino", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Books Collection");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Reading");

        to_read_label.setForeground(new java.awt.Color(255, 255, 255));
        to_read_label.setText("To-Read");

        to_read_list.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        to_read_list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                to_read_listMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(to_read_list);

        reading_list.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        reading_list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reading_listMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(reading_list);

        create_book_btn.setText("Add New Book");
        create_book_btn.setBorder(null);
        create_book_btn.setBorderPainted(false);
        create_book_btn.setFocusPainted(false);
        create_book_btn.addActionListener(this::create_book_btnActionPerformed);

        finished_label.setForeground(new java.awt.Color(255, 255, 255));
        finished_label.setText("Finished");

        finished_list.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        finished_list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                finished_listMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(finished_list);

        search_btn.setText("Search Book");
        search_btn.addActionListener(this::search_btnActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(create_book_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(search_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(to_read_label)
                        .addGap(226, 226, 226)
                        .addComponent(finished_label)
                        .addGap(159, 159, 159))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(search_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(create_book_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(to_read_label)
                    .addComponent(finished_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane1))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 810, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void finished_listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_finished_listMouseClicked
        // TODO add your handling code here:
        list_mouse_clicked(finished_list);
    }//GEN-LAST:event_finished_listMouseClicked
    
    private void search_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_btnActionPerformed
        manager.setSearchBookWindow(new SearchBook(manager.getDBOperator(), manager));
        this.setVisible(false);
    }//GEN-LAST:event_search_btnActionPerformed

    private void create_book_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_book_btnActionPerformed
        manager.setCreateBookWindow(new CreateBook(manager.getDBOperator(), manager, new Validator()));
        this.setVisible(false);
    }//GEN-LAST:event_create_book_btnActionPerformed

    private void reading_listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reading_listMouseClicked
        list_mouse_clicked(reading_list);
    }//GEN-LAST:event_reading_listMouseClicked

    private void to_read_listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_to_read_listMouseClicked
    // TODO add your handling code here:
        list_mouse_clicked(to_read_list);
    }//GEN-LAST:event_to_read_listMouseClicked

    private void list_mouse_clicked(JList list_name)
    {  
        int book_id = db_operator.getBookId(list_name.getSelectedValue().toString());
        Book book = db_operator.getFullBookDetails(book_id);
        manager.setSingleBookWindow(new SingleBookInfo(book, manager, new Validator(), db_operator));
        this.dispose();
        
        
// saved before the resultset was closed
      //  UserBook user_book = new UserBook(manager.getDBOperator().getUser(), book.getBookId(), )
       // manager.setPreviousWindow("BookCollection");
        //manager.setSingleBookWindow(new SingleBookInfo(book, manager));
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton create_book_btn;
    private javax.swing.JLabel finished_label;
    private javax.swing.JList<String> finished_list;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JList<String> reading_list;
    private javax.swing.JButton search_btn;
    private javax.swing.JLabel to_read_label;
    private javax.swing.JList<String> to_read_list;
    // End of variables declaration//GEN-END:variables
    private WindowManager manager;
    private DBOperator db_operator;
}
