/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package code_files;
import java.sql.Statement;
import java.sql.ResultSet;
import java.io.File;
import javax.swing.ImageIcon;
import java.io.FileInputStream;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JLabel;

/**
 *
 * @author JessicaS
 */
public class CreateBook extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CreateBook.class.getName());

    /**
     * Creates new form BookDetails
     */
    public CreateBook(DBOperator db_operator, WindowManager manager, Validator validator) { // neef a reference to db_operator which alr has the connection
        initComponents();
        this.setLocationRelativeTo(null);
        this.pack();
        this.db_operator = db_operator;
        this.manager = manager;
        this.validator = validator;
        img_file_chooser.setVisible(false);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        img_file_chooser = new javax.swing.JFileChooser();
        option_pane = new javax.swing.JOptionPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        book_image = new javax.swing.JLabel();
        author_text = new javax.swing.JTextField();
        book_title = new javax.swing.JLabel();
        title_text = new javax.swing.JTextField();
        num_of_pages = new javax.swing.JLabel();
        num_pages_text = new javax.swing.JTextField();
        book_author = new javax.swing.JLabel();
        create_btn = new javax.swing.JButton();
        upload_file_btn = new javax.swing.JButton();
        book_img = new javax.swing.JLabel();
        back_btn = new javax.swing.JButton();

        img_file_chooser.setApproveButtonText("");
        img_file_chooser.setApproveButtonToolTipText("");
        img_file_chooser.setDialogTitle("");
        img_file_chooser.addActionListener(this::img_file_chooserActionPerformed);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 500));
        setSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(158, 118, 118));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));

        jLabel1.setFont(new java.awt.Font("Palatino", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CREATE NEW BOOK");

        book_image.setForeground(new java.awt.Color(255, 255, 255));
        book_image.setText("Image FIle");

        author_text.addActionListener(this::author_textActionPerformed);

        book_title.setForeground(new java.awt.Color(255, 255, 255));
        book_title.setText("Title");

        title_text.addActionListener(this::title_textActionPerformed);

        num_of_pages.setForeground(new java.awt.Color(255, 255, 255));
        num_of_pages.setText("Number of Pages");

        num_pages_text.addActionListener(this::num_pages_textActionPerformed);

        book_author.setForeground(new java.awt.Color(255, 255, 255));
        book_author.setText("Author");

        create_btn.setText("Create");
        create_btn.addActionListener(this::create_btnActionPerformed);

        upload_file_btn.setText("Upload File");
        upload_file_btn.addActionListener(this::upload_file_btnActionPerformed);

        book_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/code_files/_.jpeg"))); // NOI18N

        back_btn.setText("Back to Collection");
        back_btn.addActionListener(this::back_btnActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(book_title, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(title_text, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(num_pages_text, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(num_of_pages, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(book_author, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(author_text, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(book_image, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(upload_file_btn))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(book_img, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(135, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(create_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(book_title, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(title_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(num_of_pages, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(num_pages_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(book_author, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(author_text, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(book_image, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(upload_file_btn)
                                .addGap(38, 38, 38))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(book_img, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addComponent(create_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 770, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void author_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_author_textActionPerformed
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_author_textActionPerformed

    private void num_pages_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num_pages_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num_pages_textActionPerformed

    private void create_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_btnActionPerformed
    
        ArrayList<String> labels = new ArrayList<>();
        labels.add(title_text.getText());
        labels.add(author_text.getText());
        labels.add(num_pages_text.getText());
        if(validator.isEmpty(labels)) // First check if any fields are empty
        {
            manager.showErrorMessage(option_pane, "Cannot leave any fields empty!");
        }
        else if (!validator.isNumeric(num_pages_text.getText())) // Then check if number of pages is an INTEGER
        {
            manager.showErrorMessage(option_pane, "Enter an integer number of pages!");
        }
        else
        {
            Book book = new Book();
            book.setName(title_text.getText());
            book.setAuthor(author_text.getText());
            book.setNumPages(Integer.parseInt(num_pages_text.getText()));
            if(book.getImage() != null)
            {
                book.setImage(convertFiletoByte(img_file));
            }
            book.setTotalUsersRead(0);
            int book_valid = db_operator.createBook(book);
            switch(book_valid)
            {
                case 1: 
                    manager.showConfirmMessage(option_pane, "Book added successfully!");
                    break;
                case 0:
                    manager.showErrorMessage(option_pane, "Book already exists!");
                    break;
                case -1:
                    manager.showErrorMessage(option_pane, "Unable to add the book.");
                    break;
            }
       
        }
    }//GEN-LAST:event_create_btnActionPerformed

    private void title_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_title_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_title_textActionPerformed

    private void img_file_chooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_img_file_chooserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_img_file_chooserActionPerformed

    private void upload_file_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upload_file_btnActionPerformed
        // TODO add your handling code here:
        
        // select the users OWN file directory 
        String path = System.getProperty("user.dir");
        File working_directory = new File(path);
        img_file_chooser.setCurrentDirectory(working_directory);
       
        img_file_chooser.setVisible(true);
        
        img_file_chooser.showOpenDialog(jPanel1);
        img_file_chooser.setApproveButtonText("Save");

        if(img_file_chooser.getSelectedFile() != null)
        {
           System.out.println(img_file_chooser.getSelectedFile().getPath());
           img_file = img_file_chooser.getSelectedFile();
            book_img.setIcon(new ImageIcon(img_file.getPath()));
        
        
        
        book_img.setIcon(new ImageIcon(img_file.getPath()));
        }
        // change image to the selected file

    }//GEN-LAST:event_upload_file_btnActionPerformed
   public byte[] convertFiletoByte(File file) // returns the byte contents 
   {
       try{
           FileInputStream input = new FileInputStream(file); // holds file contents
           return input.readAllBytes();  
        }  
        catch(IOException e)
        {
               System.out.println("Something went wrong while trying to convert the file");
               e.printStackTrace();
        }
       return null;
   }

    
    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        // TODO add your handling code here:
        manager.setBookCollectionWindow(new BookCollection(manager, db_operator));
        this.dispose();
    }//GEN-LAST:event_back_btnActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField author_text;
    private javax.swing.JButton back_btn;
    private javax.swing.JLabel book_author;
    private javax.swing.JLabel book_image;
    private javax.swing.JLabel book_img;
    private javax.swing.JLabel book_title;
    private javax.swing.JButton create_btn;
    private javax.swing.JFileChooser img_file_chooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel num_of_pages;
    private javax.swing.JTextField num_pages_text;
    private javax.swing.JOptionPane option_pane;
    private javax.swing.JTextField title_text;
    private javax.swing.JButton upload_file_btn;
    // End of variables declaration//GEN-END:variables
    private DBOperator db_operator; 
    private File img_file;
    private WindowManager manager;
    private Validator validator;
}

