package code_files;

import code_files.AnnouncementsPage;
import code_files.AnnouncementsPage;
import java.time.LocalDate;
import javax.swing.JOptionPane;



public class Menu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Menu.class.getName());


    public Menu(WindowManager manager, User user) {
        this.manager = manager;
        this.user = user;
        streak_msg_clicked = false;
        initComponents();
        configureWelcomeMessage();
        setLocationRelativeTo(null); //centres it
        setResizable(false);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        option_pane = new javax.swing.JOptionPane();
        jPanel1 = new javax.swing.JPanel();
        announcements_btn = new javax.swing.JButton();
        book_list_menu_btn = new javax.swing.JButton();
        exit_btn = new javax.swing.JButton();
        welcome_label = new javax.swing.JLabel();
        user_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(89, 69, 69));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 600));

        announcements_btn.setBackground(new java.awt.Color(129, 91, 91));
        announcements_btn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        announcements_btn.setForeground(new java.awt.Color(224, 118, 118));
        announcements_btn.setText("ANNOUNCEMENTS");
        announcements_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(89, 69, 69), new java.awt.Color(89, 69, 69), new java.awt.Color(89, 69, 69), new java.awt.Color(89, 69, 69)));
        announcements_btn.setPreferredSize(new java.awt.Dimension(220, 120));
        announcements_btn.addActionListener(this::announcements_btnActionPerformed);

        book_list_menu_btn.setBackground(new java.awt.Color(129, 91, 91));
        book_list_menu_btn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        book_list_menu_btn.setForeground(new java.awt.Color(224, 118, 118));
        book_list_menu_btn.setText("BOOK LIST");
        book_list_menu_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(89, 69, 69), new java.awt.Color(89, 69, 69), new java.awt.Color(89, 69, 69), new java.awt.Color(89, 69, 69)));
        book_list_menu_btn.setPreferredSize(new java.awt.Dimension(220, 120));
        book_list_menu_btn.addActionListener(this::book_list_menu_btnActionPerformed);

        exit_btn.setBackground(new java.awt.Color(255, 248, 234));
        exit_btn.setForeground(new java.awt.Color(154, 69, 69));
        exit_btn.setText("Log Out");
        exit_btn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(72, 69, 69), 1, true));
        exit_btn.setPreferredSize(new java.awt.Dimension(120, 40));
        exit_btn.addActionListener(this::exit_btnActionPerformed);

        welcome_label.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        welcome_label.setForeground(new java.awt.Color(255, 255, 255));
        welcome_label.setText("Welcome, ");

        user_label.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        user_label.setForeground(new java.awt.Color(255, 255, 255));
        user_label.setText("Insert User Here");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(exit_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(welcome_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(user_label))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(book_list_menu_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(announcements_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(215, 215, 215))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(welcome_label)
                            .addComponent(user_label)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(exit_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(127, 127, 127)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(book_list_menu_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(announcements_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(259, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void configureWelcomeMessage()
    {
        user_label.setText(user.getName());
    }
    
    public void setUser(User user)
    {
        this.user = user;
    }
    
    
    private void exit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_btnActionPerformed
        // TODO add your handling code here:
        //return to login screen
        if(manager.getLoginWindow() == null)
        {
            manager.setLoginWindow(new Login(manager, new Validator(), manager.getDBOperator()));
            // mistake: passed in a completely new db operator that didnt change the user properly w the setter method
        }
      
        manager.getLoginWindow().setVisible(true);
        this.setVisible(false); 
    }//GEN-LAST:event_exit_btnActionPerformed

    private void book_list_menu_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book_list_menu_btnActionPerformed
            LocalDate today = LocalDate.now(); // local time

            if(user.getLastDateRead() != null)
            {
                if(streak_msg_clicked == false && !user.getLastDateRead().equals(today.toString()))
                {
                    int input = JOptionPane.showConfirmDialog(null, "Have you read a chapter of a book today?", "Streak Tracker", JOptionPane.YES_NO_OPTION);
                    if(input == JOptionPane.YES_OPTION) 
                    {
                        // check if the user didn't log their streak the day before & reset if so
                        if(!user.getLastDateRead().equals((today.minusDays(1)).toString())) 
                        {
                            user.setStreak(0);
                        }
                        else 
                        {
                            user.setStreak(user.getStreak() +1);
                            // call db method to update last date read to today
                            manager.getDBOperator().saveLastDateRead();
                        }
                        manager.showPlainMessage(option_pane, "Your streak is " + user.getStreak());
                        // update the streak 
                        manager.getDBOperator().saveStreak();
                        streak_msg_clicked = true;
                    }
                }
            }

        if(manager.getBookListMenuWindow() == null)
        {
            manager.setBookListMenuWindow(new BookListMenu(manager));
        }
        manager.getBookListMenuWindow().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_book_list_menu_btnActionPerformed

    private void announcements_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_announcements_btnActionPerformed

        //manager.getDBOperator().setUser(user);
        manager.getDBOperator().setUser(user);

        if(manager.getAnnouncementsWindow() == null)
        {
            manager.setAnnouncementsWindow(new AnnouncementsPage(manager, manager.getDBOperator(), new Validator()));
        }
       
        manager.getAnnouncementsWindow().roleCheck();
        manager.getAnnouncementsWindow().repaint();
        manager.getAnnouncementsWindow().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_announcements_btnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton announcements_btn;
    private javax.swing.JButton book_list_menu_btn;
    private javax.swing.JButton exit_btn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JOptionPane option_pane;
    private javax.swing.JLabel user_label;
    private javax.swing.JLabel welcome_label;
    // End of variables declaration//GEN-END:variables
    private WindowManager manager;
    private User user;
    private boolean streak_msg_clicked;
}
